version: '3.8'

volumes:
  mongo_vol:

networks:
   my-netservivces:
      driver: bridge

services:
  python:
   image: priscilaalv/rotten-potatoes:v1
   ports:
   - 5000:5000
   networks:
    - my-netservivces
   restart: always
   environment:
     MONGODB_HOST: mongodb
     MONGODB_PORT: 27017
     MONGODB_USERNAME: mongouser
     MONGODB_PASSWORD: mongopwd

  mongodb:
    image: mongo:5.0.6
    ports: 
    - 27017:27017
    networks:
    - my-netservivces
    volumes:
    - mongo_vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd